VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'ubuntu/trusty64'

  config.vm.network :private_network, ip: '192.168.33.10'

  config.vm.provision :shell, :path => 'init.sh', privileged: false

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ['modifyvm', :id, '--natdnsproxy1', 'off']
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'off']
  end

  config.vm.synced_folder '../', '/home/vagrant/app', \
    create: true, owner: 'vagrant', group: 'vagrant', \
    mount_options: ['dmode=777,fmode=666']
end
