default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: reversal
  username: root
  password: pw

development:
  <<: *default
  host: boot2docker

test:
  <<: *default
  host: db

production:
  <<: *default
  password: <%= ENV['REVERSAL_DATABASE_PASSWORD'] %>
  host: db
