default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: boot2docker
  username: root
  password: pw

development:
  <<: *default
  database: reversal

test:
  <<: *default
  database: test

production:
  <<: *default
  database: reversal
